In [1]:
# print("hello world")

In [2]:
# a = 1

In [3]:
# a

In [4]:
# b = [1,2,3,4,5]

In [5]:
# b*2

In [6]:
# # 영어 타자연습 프로그램
# #타자연습 게임
# import random
# import time

# word = ['sky', 'earth', 'moon', 'flower', 'tree', 'apple', 'grape',
#         'garlic', 'onion', 'potato']

# with open("word.txt",'r') as f:
#     word = f.read().split() #전역변수이다!

# n = 1
# input("[타자 게임] 준비되면 엔터!")
# start = time.time()

# while n < 11:
#     print("문제",n)
#     question = random.choice(word) #choice는 중복 나온다!
#     print(question)
#     user = input()
#     if question == user : 
#         print("통과!")
#         n += 1
#     else:
#         print("오타! 다시 도전!")

# end = time.time()
# et = end - start
# print(f"타자 시간: {et: .2f}초")

In [7]:
import numpy as np
x = np.array([3,1,2,4]) #np는 하나의 타입만 지원한다!
print(x)
print(type(x))
print(type([3,1,2]))

[3 1 2 4]
<class 'numpy.ndarray'>
<class 'list'>


In [8]:
c = [[1],[1,2]]
d = np.array([[1,3], [1,2]]) # 배열 내의 갯수(동일한 차원)가 같아야 한다

for x,y in d:
    print(x,y)

1 3
1 2


In [9]:
x = np.array([1.0,2.0,3.0]) #문자는 연산 불가!
y = np.array([2.0,4.0,6.0]) #숫자만 연산 가능하다!
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(y/2.0) #스칼라 값으로 나누기

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[1. 2. 3.]


In [10]:
print(x.shape)
print(x.dtype)
print(d.shape)

(3,)
float64
(2, 2)


In [11]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)
print(a.shape)

b = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(b.ndim)
print(b.shape)

c = np.array([[[1,2],[2,2]],[[3,1],[4,1]],[[5,3],[6,4]]])
print(c.ndim)
print(c.shape)

2
(3, 2)
3
(3, 2, 1)
3
(3, 2, 2)


In [12]:
np.dot(4,2)

8

In [27]:
ndar1 = np.array([1,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)

16

In [14]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [30]:
# #이렇게 하면 안된다!
ndar1 = np.array([1,2],[3,4])
ndar2 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar2)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [16]:
ndar1 = np.array([[1,2],[3,4]])

print(ndar1.shape)
print(ndar1.ndim)
a = ndar1.flatten()

print(a.ndim)
print(ndar1)
print(a)

(2, 2)
2
1
[[1 2]
 [3 4]]
[1 2 3 4]


In [17]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)
ndarr.reshape(6,1)
# ndarr.reshape(1,6)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [18]:
np.random.randint(5, size = (2,4)) #4까지

array([[4, 0, 3, 1],
       [1, 4, 4, 2]])

In [19]:
np.random.rand(2,4)

array([[0.60583727, 0.60380442, 0.88230315, 0.03687386],
       [0.65801782, 0.54035677, 0.72859048, 0.89745582]])

In [242]:
#최신동향! 요즘엔 이렇게 한다고함
rng = np.random.default_rng()

In [21]:
rng.random() # 0~1사이값(1포함 x)

0.06391194293629288

In [22]:
rng.integers(0,10,(2,4))

array([[0, 7, 9, 3],
       [9, 7, 4, 6]], dtype=int64)

In [23]:
#중요!!
ndarr = np.array([[6,3],[5,2],[4,1]]) #차원이 같아야 한다
ndarr > 4
# ndarr[ndarr > 1]

array([[ True, False],
       [ True, False],
       [False, False]])

In [24]:
ndarr[0:]

array([[6, 3],
       [5, 2],
       [4, 1]])

In [25]:
([[ True, False],
       [ True, False],
       [True, False]])

[[True, False], [True, False], [True, False]]

In [31]:
# ndarr[([[ True, False],
#        [ True, False],
#        [True, False]])]

In [1]:
# ndarr1 = np.array([[1,2],[3,4],[5,6]])
# ndarr2 = np.array([[1,2,3],[3,4,5]])
ndarr1 = np.array([1,2])
ndarr2 = np.array([2,2])
# np.matmul(ndarr1,ndarr2)
print(np.cross(ndarr1,ndarr2))

# print(ndarr.ndim)
# print(ndarr.shape)
# ndarr[ndarr>3]

NameError: name 'np' is not defined

In [127]:
#실습 Numpy 모듈 사용하기 1
import numpy as np
import random
#1
array = np.zeros(10)
print(array)

#2
array[4] = 1
print(array)

#3
array2 = np.arange(10,31)
print(array2)

#4
array3 = np.random.randint(100,size=(2,2))
print(array3)

#sol2)
rng = np.random.default_rng(1) #1자리에 아무거나 넣어도 상관없다! <-seed값 넣은거임 : 특정 seed를 넣었을때 값이 고정된다
array3 = rng.integers(0,100,(2,2)) # <- 윗줄이랑 같은곳에서 돌리면 계속 같은 값만 나온다! 따로 떨어뜨려야함
print(array3)

#5
array4 = np.random.rand(2,4)
print(array4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[ 5 34]
 [96 87]]
[[47 51]
 [75 95]]
[[0.09555354 0.44267407 0.86070143 0.24708505]
 [0.5846946  0.44686075 0.5372866  0.57181178]]


In [213]:
#실습2
#6
print("실습6")
array = np.arange(35,75)
ch_array = array.reshape(10,4)
print(ch_array)

#7
print("실습7")
print(ch_array[::-1])

#8
print("실습8")
ch2_array = ch_array[1:-1,2:]
print(ch2_array)


실습6
[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
실습7
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
실습8
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [245]:
#9
print("9번 문제")
ch3_array = ch_array[:,-1]
print(ch3_array)

#9-1
print("9-1번 문제")
ch3_array = ch_array[:,-1:]
print(ch3_array)

#10
print("10번 문제")
print(ch3_array[::-1])

#11
print("11번 문제")
new_array = np.random.randint(1,50, size = (5,6))
print(new_array[new_array % 2 == 0])


9번 문제
[38 42 46 50 54 58 62 66 70 74]
9-1번 문제
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
10번 문제
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
11번 문제
[48  2 10 46 24  2 22 30 16 38 12 22 32 34 12 28 20  8]


In [248]:
import numpy as np

a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a,0)
print(expanded)
print(expanded.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [250]:
a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a,1)
print(expanded)
print(expanded.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [252]:
a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a,2)
print(expanded)
print(expanded.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [254]:
np_ones = np.ones((1,2,1,3))
print(np_ones)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]


In [258]:
sq = np.squeeze(np_ones) #아무것도 안하면 1차원인것을 모두 없앤다.T
print(sq)
print(sq.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [275]:
#중복 제거
a = [1,2,2,3,3,3,4,4] #무조건 index가 가장먼저, counts가 다음으로 나옴
u_a, counts,index, = np.unique(a, return_index=True, return_counts=True) #괄호안에 입력된 순서 상관없이 index가 가장 먼저 나옴
print(u_a)
print(index)
print(counts)

[1 2 3 4]
[1 2 3 2]
[0 1 3 6]


In [277]:
def add(a=1 ,b=1):
    return a,b,a+b

a,b,sum = add(2,3)
print(a,b,sum)

2 3 5


In [345]:
#정렬 argsort()중요!!
a = np.array([1,1,4,2,3])
b = np.sort(a) # a[np.argsort(a)]와 같은 뜻임
print(f"a : {a}")
print(f"b : {b}")
c = np.argsort(a)
print(f"c : {c}")
print(f"cc : {a[c]}")
print(f"원래 리스트 : {a[c.sort()].flatten()}")
a.sort()
print(f"a : {a}")

a : [1 1 4 2 3]
b : [1 1 2 3 4]
c : [0 1 3 4 2]
cc : [1 1 2 3 4]
원래 리스트 : [1 1 4 2 3]
a : [1 1 2 3 4]


In [284]:
# 그 밖의 유용한 함수
a = np.array([1,4,2,3])
np.mean(a)

2.5

In [286]:
np.max(a)

4

In [287]:
np.var(a)

1.25

In [289]:
np.prod(a)

24

In [292]:
np.median(a) #중앙값    

2.5

In [294]:
np.std(a)

1.118033988749895

In [304]:
import numpy as np #axis= 0 : 행 (|)  axis=1 : 열 (ㅡ)

x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:,::2] = -99
print(x)

print("")
a = np.sort(x,axis = 0)
print(a)

print("")
b = np.sort(x,axis = 1)
print(b)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]

[[-99   1 -99   3 -99]
 [-99   6 -99   8 -99]
 [  0  11   2  13   4]]

[[  0   1   2   3   4]
 [-99 -99 -99   6   8]
 [-99 -99 -99  11  13]]


In [372]:
#실습 numpy모듈 사용하기 2
import numpy as np
array = np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])

#1
print("1번")
u_a = np.unique(array)
print(u_a)

#2
print("\n2번")
u_a_M = np.max(u_a)
u_a_m = np.min(u_a)
u_a_mean = np.mean(u_a)
print(f"최대값 : {u_a_M}, 최소값 : {u_a_m}, 평균값 : {u_a_mean}")

#3
print("\n3번")
u_a_sum = np.sum(u_a)
print(u_a_sum)

#4
print("\n4번")
u_a_median = np.median(array)
print(u_a_median)




1번
[  1   2   3   4   5   7   8   9  10  11  24 100]

2번
최대값 : 100, 최소값 : 1, 평균값 : 15.333333333333334

3번
184

4번
5.0


In [377]:
#실습3
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
print(x)
print(x[-2:,-2:])

#1
print("\n1번")
x_max = np.max(x[:,0],axis=0)
x_min = np.min(x[:,0],axis=0)
x_mean = np.mean(x[:,0],axis=0)
print(f"최대값 : {x_max}, 최소값 : {x_min}, 평균값 : {x_mean}")

#2
print("\n2번")
x_sum = np.sum(x[1:2,:])
print(f"2행 모든 합: {x_sum}")

# #3
print("\n3번")
array2 = np.argsort(array)
a = array[array2]
print(a[::-1])


[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
[[  8 -99]
 [ 13 -99]]

1번
최대값 : 0, 최소값 : -99, 평균값 : -66.0

2번
2행 모든 합: -283

3번
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
